### ISSUE TITLE
World mirrors break rendering after world change.

### ISSUE THREAD

**Issue by Shanesan** [normalizedcrow/LavaLamp#1]
- Open up personal mirror and observe working shader in the mirror
- Change worlds
- Personal Mirror, and other mirrors, no longer render the internals of the shader, just the transparency

Using version 1.1. Image: https://i.imgur.com/y2GpQJc.png

**Comment by normalizedcrow** [comment]
Hey, I'm having trouble reproducing this issue. Could you share which worlds in particular you were switching between?

**Comment by Shanesan** [comment]
Hi normalizedcrow! This happens in the Personal Mirror in the UI, Old Hub mirror, and almost every mirror I've seen. I've seen it come in fine too, and have seen it come in mostly broken: for example, looking at the personal mirror, there is a chance to see the proper reflection if you move your head around enough (but it must be exact).

This does NOT happen in cameras. I'll see if I can get a recording.

I will also try another home world, maybe that's what's buggin' it.

**Comment by Shanesan** [comment]
Here are my shader settings for your reference.
![LavaLamp_Settings](https://user-images.githubusercontent.com/22644226/200147254-d3c508bf-23f0-4552-96bd-80dd5970d455.PNG)

**Comment by normalizedcrow** [comment]
Thanks! If your current home world is public, could you post a link to it in case it is something specific to that world causing it?

In the meantime, you should be able to sidestep this issue by disabling the "Lava Depth Intersection" setting.

**Comment by Shanesan** [comment]
Hi! I searched for the Lava Depth Intersection setting but my eyes must be getting bad. What section is that under?

**Comment by normalizedcrow** [comment]
Sorry for the late reply, if you haven't found it yet it's under the advanced options at the very bottom of the material

**Comment by normalizedcrow** [comment]
Finally tracked down the cause of this There's now a "Force Depth Buffer On" prefab you can put on your avatar to make Lava Depth Intersection not have this issue.
