### ISSUE TITLE
Shader does not clamp down emission value, creates flashing sparkles in badly lit worlds

### ISSUE THREAD

**Issue by Shanesan** [normalizedcrow/LavaLamp#2]
Due to VRChat's ability for anyone to make awfully-lit worlds, shaders have to clamp their maximum emission value as certain bloom configurations can cause them to flashbang. Currently lavalamp does not, and you become a great sparkly mess in certain lighting configurations.

**Comment by Shanesan** [comment]
(this might be from changing the upper and lower lighting in the shader to a higher than 1.0 intensity in HDR)

**Comment by normalizedcrow** [comment]
yeah I'm not going to clamp the overall brightness of the lava since that would be functionally identical to just lowering the intensity of the top and bottom lights but I am adding an option to clamp the brightness of specular highlights

**Comment by Shanesan** [comment]
That sounds like it'll work! Thank you!!

**Comment by normalizedcrow** [comment]
there's a new Max Specular Highlight Brightness setting in the advanced options that should handle this
