### ISSUE TITLE
Prop renders broken in-game (world, not avatar)

### ISSUE THREAD

**Issue by NanoBunTV** [normalizedcrow/LavaLamp#3]
I've been trying to get this working for 5 hours now, at this point I don't know if I broke something or if this is actually a bug.

My lava lamp prop in my world simply doesn't work in-game.

![Unity_EI25xNubKN](https://user-images.githubusercontent.com/38265095/204115272-744eeda8-92a0-48c5-b1a0-4bdbdb5e4192.png)
![VRChat_UdeVvqGHe1](https://user-images.githubusercontent.com/38265095/204115273-c1289da8-9d5e-49a3-ab92-cc703e8b8862.png)

Heres my settings, I've also tried with and without the sdf and bind textures.
![Unity_R2AxG6bZkM](https://user-images.githubusercontent.com/38265095/204115278-7461e73b-d9c5-4935-afce-d9f9f9513b6a.png)

Heres also my unity package with the specific mesh I'm using. (shader v1.2)
[LampIsBROKE.zip](https://github.com/normalizedcrow/LavaLamp/files/10097331/LampIsBROKE.zip)

**Comment by normalizedcrow** [comment]
Those settings all look correct, the only think I can think is maybe try disabling GPU Instancing? I'll take a look at the mesh

**Comment by normalizedcrow** [comment]
Alright, I figured it out. The game object with the renderer using the lava material on it needs to not be "Batching Static." I'll add a warning in the instructions about that for the future.

**Comment by normalizedcrow** [comment]
Alright, I figured it out. The game object with the renderer using the lava material on it needs to not be "Batching Static." I'll flag the shader to disable batching.
